version: "3.8"
services:
  dev-mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PW}
    restart: always
    networks:
      - lesson
networks:
  lesson:
