version: 2.1

jobs:
  build-and-test:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: go mod download
      - run:
          name: "Build"
          command: go build -o app
      - run:
          name: "Run Tests"
          command: go test ./...

  check-lint:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run:
          name: "Install errcheck tool"
          command: go install github.com/kisielk/errcheck@latest
      - run:
          name: "Set GOPATH/bin to PATH"
          command: echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> $BASH_ENV
      - run:
          name: "Run go vet"
          command: go vet ./...
      - run:
          name: "Run errcheck"
          command: errcheck ./...
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  code-quality-check:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: "Install golint"
          command: go install golang.org/x/lint/golint@latest
      - run:
          name: "Set GOPATH/bin to PATH"
          command: echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> $BASH_ENV
      - run:
          name: "Run golint"
          command: golint ./...

  code-format-check:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: "Check code formatting with gofmt"
          command: gofmt -l -e .

  security-check:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: "Setup Go environment"
          command: |
            echo 'export GOPATH=~/go' >> $BASH_ENV
            echo 'export GOROOT=$(go env GOROOT)' >> $BASH_ENV
            echo 'export PATH=$PATH:$(go env GOPATH)/bin:$GOROOT/bin' >> $BASH_ENV
      - run:
          name: "Clear dependencies cache"
          command: go clean -modcache
      - run:
          name: "Install dependencies"
          command: go mod download
      - run:
          name: "Build the project"
          command: go build ./...
      - run:
          name: "Install gosec"
          command: go install github.com/securego/gosec/cmd/gosec@latest
      - run:
          name: "Set GOPATH/bin to PATH"
          command: echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> $BASH_ENV
      - run:
          name: "Run gosec"
          command: gosec ./...

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - check-lint:
          requires:
            - build-and-test
      - code-quality-check:
          requires:
            - build-and-test
      - code-format-check:
          requires:
            - build-and-test
      - security-check:
          requires:
            - build-and-test
