version: 2.1

jobs:
  build-and-test:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: go mod download
      - run:
          name: "Build"
          command: go build -o app
      - run:
          name: "Run Tests"
          command: go test ./...
